-- ============================================================
--  SIT Campus App - Full Database Seed Script
--  Run this in your Supabase SQL Editor.
--  It will create the necessary tables and inject login credentials.
-- ============================================================

-- 1. Create the Departments table if it doesn't exist
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

-- 2. Create the Admins table if it doesn't exist
CREATE TABLE IF NOT EXISTS admins (
    email VARCHAR(255) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Inject Department Accounts (Password for all: dept@123)
INSERT INTO departments (name, type, email, password_hash) VALUES
  ('Electrical Department', 'Electrical', 'electrical@sitpune.edu.in', '$2a$10$scmQR9ZYWODsrQUpgYvL8.CZCom4gnS9fkiKvdc4NPfbiqBlI7oJm'),
  ('IT Department', 'IT', 'it@sitpune.edu.in', '$2a$10$/oXEBwDz2br4VJJmQkQdQOPQLmlANa3SnCUkzantg4hwr8ILRgcva'),
  ('Cleaning Department', 'Cleaning', 'cleaning@sitpune.edu.in', '$2a$10$TkULSCG4apDJflbCFoZzwO53oL1krFQu0PhtQoOZ.AEbKN/Z3cbkC'),
  ('Hostel Department', 'Hostel', 'hostel@sitpune.edu.in', '$2a$10$UT1IGZct3WQHyjp.FzgVM.dLyMOknM7dPaZVAQnpqN6RAEYO4s5ji'),
  ('Plumbing Department', 'Plumbing', 'plumbing@sitpune.edu.in', '$2a$10$7Zkilc/pDMdazXBipVl6IOi/qqIvWmeinURjLFD/a63ke7plABay2'),
  ('General Department', 'General', 'general@sitpune.edu.in', '$2a$10$B/pxBGshJXG8zR9/1WfsU.wi5Q3Wk6bl3vwJD4O4/rmdIFmuVzwRq')
ON CONFLICT (type) DO NOTHING;

-- 4. Inject System Admin Account (Password: admin@123)
INSERT INTO admins (email, first_name, last_name, password_hash)
VALUES ('admin@sitpune.edu.in', 'System', 'Administrator', '$2a$10$w8uD9Zq/0uG3kL9oYn.eP.7Zz6VdYt7hW/lQ6kO5O6/JcWk8P6z2S')
ON CONFLICT (email) DO NOTHING;
